# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f16bbaf68dc2c144d921704612d622da4d79a4ff8153cd6e480f83f031274234b3a17dab1d6cd5224726c66c5c32be6d95656bfec4089b351338d6d233d0395e

test:
  secret_key_base: ba0c644e6bf43f3e82ba3872d74ffe50cef1d14843b732fb470659e5f594b8474d9f2eb0e588e8598a7712d9cc7d994ebb2eece8ebd89ef5cc60f92f406b2e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
